(define (run)
  (assert (equal? (ip-deriv '(3 + x) 'x)
                  1))
  (assert (equal? (ip-deriv '(x + y) 'x)
                  1))
  (assert (equal? (ip-deriv '((x * y) * (x + 3)) 'x)
                  '((x * y) + (y * (x + 3)))))
  (assert (equal? (i-deriv '(3 + x) 'x)
                  1))
  (assert (equal? (i-deriv '(x + y) 'x)
                  1))
  (assert (equal? (i-deriv '(x * y * (x + 1)) 'x)
                  '(x * y + y * (x + 1))))
  (assert (equal? (i-deriv '(x * (x + 1) * (x + 2)) 'x)
                  '(x * (x + 1 + x + 2) + (x + 1) * (x + 2))))
  (assert (equal? (i-deriv '(x * x + 1 * x + 2) 'x)
                  '(x + x + 1)))
  "All tests passed!"
)
